name: 'Airdb Actions'
description: 'Airdb Container Actions'
author: 'deancn'

branding:
  color: 'yellow'
  icon: 'bell'

inputs: 
  myCommand:
    description: 'airdb github command'
    default: 'bash -x /entrypoint.sh'
runs:
  using: 'docker'
  image: 'docker://airdb/actions'
  env:
    GITHUB_TOKEN: $GITHUB_TOKEN
  args:
    - ${{ inputs.myCommand }}
