name: "test env"
on:
  push:

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:

      - name: airdb actions
        id: actionID
        uses: airdb/actions@v0.0.2
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
