name: "actions_test"
on:
  push:

jobs:
  actions_test:
    runs-on: ubuntu-latest
    steps:
      - name: actions_test
        id: actionID
        uses: airdb/actions/test@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          myCommand: "bash -x /entrypoint.sh github-pages"
