name: "airdb-actions"
on:
  push:

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: airdb actions
        id: actionID
        uses: airdb/actions/test@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          myCommand: "bash -x /entrypoint.sh github-pages"
